---
- name: INSTALLING APACHE2
  hosts : [NODE2]
  remote_user: victor
  become: true

  vars_files:
    - var.yml

  tasks:
  - name: GET UPDATES
    apt:
     update_cache: yes

  - name: INSTALLING APACHE2
    apt:
     name: apache2
     state: latest

  - name: START SERVICES
    service:
      name: apache2
      state: restarted
      enabled: yes
