---
- name: samplebook
  hosts : [NODE2]
  remote_user: victor
  become: true

  vars_files:
    - var.yml

  tasks:
  - name: Start docker
    command: sudo systemctl stop jenkins

#  - name: Deploy app
#    docker_compose:
#      project_src: MERN-Stack-App
#      build: no
#    register: output

