---
- name: DOCKER_COMPOSE
  hosts : [NODE2]
  remote_user: victor
  become: true

  vars_files:
    - var.yml

  tasks:
     - name: Test
       command: sudo systemctl enable jenkins
#    - name: Deploy app
#      docker_compose:
#        project_src: MERN-Stack-App
#        build: no
#      register: output

