---
- name: DOCKER_COMPOSE
  hosts : [NODE2]
  remote_user: victor
  become: true

  vars_files:
    - var.yml

  tasks:
     - name: Docker.sock
       command: sudo chmod 666 /var/run/docker.sock
     - name: Deploy App
       docker_compose:
         project_src: MERN-Stack-App
         build: no
       register: output

