• name: Configure UFW
  hosts: [NODE2]
  remote_user: victor
  become: true

  vars_files:
    - var.yml
  tasks:
    - name: Allow SSH traffic
      community.general.ufw:
        rule: allow
        port: ssh
    - name: Allow HTTP traffic
      community.general.ufw:
        rule: allow
        port: http
    - name: Enable UFW firewall
      community.general.ufw:
        state: enabled
